### ISSUE TITLE
Pull shows completed but no parts are moved.

### ISSUE THREAD

**Issue by alronefisher** [Bushfiend/TetherSE#1]
Tried with multiple containers at both near and longer distances. Build planner is cleared almost instantly, which is normal however as stated no parts are moved. 

This occurred on a dedicated server, however tether was working very well before suddenly showing this behaviour and has not returned to normal since.

**Comment by Bushfiend** [comment]
If it was on skunkworks, they specifically patched this out by adding a range check

**Comment by alronefisher** [comment]
This is on a private server that me and my friend run with minimal mods. I'm not even sure what Skunkworks is in this context.

**Comment by Bushfiend** [comment]
I am currently working on a update should speed it up considerably and hopefully fix your issue at the same time. Just for clarification, does your world have any mod components?

**Comment by alronefisher** [comment]
A few, mostly npc mods. One piston mod, but no other block mods.

**Comment by alronefisher** [comment]
I've been using it until the last several days it hasn't had any issues at all so I'm going to call this resolved. Thanks again for an amazing mod.
